add a local_only variant of the GUI test. Add pytest markers that skip the Tor-required tests if the TRAVIS env is true (which it is in Travis). Update the test wrapper script and travisci.yml to suit.

diff --git a/dev_scripts/tests b/dev_scripts/tests
--- a/dev_scripts/tests
+++ b/dev_scripts/tests
@@ -1,15 +1,25 @@
 #!/bin/bash
 
 # Designed for Linux for now
+while getopts ":lh" opt; do
+  case $opt in
+    h) HEADLESS=True
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
 
-if [[ $1 = "--headless" ]]; then
+
+if [[ $HEADLESS ]]; then
   # Run via XVFB and silence a lot of noise
-  xvfb-run py.test-3 -k 'not test_starts_with_empty_strings' | pv -i 1 -p -t -e
+  echo "Running headless tests..."
+  xvfb-run py.test-3 | egrep -v "QPainter|QWidget"
   if [ ${PIPESTATUS[0]} -ne 0 ]; then
     exit 1
   else
     exit 0
   fi
 else
-  py.test-3 -k 'not test_starts_with_empty_strings'
+  py.test-3
 fi
